services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: sudoku
      POSTGRES_USER: sudoku
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sudoku" ]
      interval: 5s
      retries: 10

  sudoku:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports: !override
      - "7000:7000"

volumes:
  pgdata:
