-- V1 - initial schema (server-spec 5).
--
-- DDL is plain SQL rather than LUtils' SqlMigrationRunner. That is a deliberate, narrow carve-out:
-- the Postgres dialect renders UUID columns as native `uuid`, which pgjdbc reports as JDBC OTHER
-- (1111), and LUtils' SqlJdbcTypeMapper has no case for it - so the runner cannot introspect the
-- schema it just created and rolls every migration back. Everything else (pooling, transactions,
-- dialect, queries) still goes through LUtils. See db/Migrations.java.
--
-- Type conventions, per the spec's mapping table:
--   entity ids      UUID (gen_random_uuid(), built into Postgres 13+, no extension needed)
--   timestamps      TIMESTAMPTZ, stored UTC and rendered per zone
--   public keys     BYTEA
--   flags           BOOLEAN
--   daily date      DATE, computed in SUDOKU_TIMEZONE at WRITE time - never derived from a
--                   timestamp at query time, or the rollover zone silently stops applying
--   ledger ids      BIGINT GENERATED BY DEFAULT AS IDENTITY
--   enum-ish        TEXT with a CHECK constraint

CREATE TABLE IF NOT EXISTS server_meta (
	key   TEXT PRIMARY KEY,
	value TEXT NOT NULL
);

CREATE TABLE users (
	id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	display_name TEXT        NOT NULL UNIQUE,
	role         TEXT        NOT NULL CHECK (role IN ('NEW', 'MEMBER', 'ADMIN')),
	created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
	-- Kicked users are revoked, never deleted: their historical results are retained (spec 7.2).
	revoked      BOOLEAN     NOT NULL DEFAULT FALSE
);

-- Supports the last-admin invariant check (spec 7.1) without scanning the table.
CREATE INDEX users_active_admins_idx ON users (role) WHERE role = 'ADMIN' AND NOT revoked;

CREATE TABLE devices (
	id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	user_id       UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
	public_key    BYTEA       NOT NULL UNIQUE,
	-- Devices need not agree: Android uses ECDSA P-256 (Keystore), other clients may use Ed25519.
	key_algorithm TEXT        NOT NULL CHECK (key_algorithm IN ('ED25519', 'ECDSA_P256')),
	label         TEXT        NOT NULL,
	created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
	last_seen_at  TIMESTAMPTZ,
	revoked       BOOLEAN     NOT NULL DEFAULT FALSE
);

CREATE INDEX devices_user_idx ON devices (user_id);

CREATE TABLE invites (
	code               TEXT PRIMARY KEY,
	-- NULL for the bootstrap invite, which predates every user.
	created_by         UUID REFERENCES users (id) ON DELETE SET NULL,
	grants_role        TEXT    NOT NULL CHECK (grants_role IN ('NEW', 'MEMBER', 'ADMIN')),
	expires_at         TIMESTAMPTZ,
	consumed_by_device UUID REFERENCES devices (id) ON DELETE SET NULL,
	consumed_at        TIMESTAMPTZ,
	revoked            BOOLEAN NOT NULL DEFAULT FALSE,
	created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE link_codes (
	code        TEXT PRIMARY KEY,
	user_id     UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
	-- Short-lived: minutes, not hours (spec 6.4).
	expires_at  TIMESTAMPTZ NOT NULL,
	consumed_at TIMESTAMPTZ,
	created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX link_codes_user_idx ON link_codes (user_id);

CREATE TABLE sessions (
	token      TEXT PRIMARY KEY,
	-- UNIQUE enforces the single-active-session rule (spec 6.2) in the schema, not just in code.
	user_id    UUID        NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
	device_id  UUID        NOT NULL REFERENCES devices (id) ON DELETE CASCADE,
	issued_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
	expires_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE auth_challenges (
	nonce      BYTEA PRIMARY KEY,
	public_key BYTEA       NOT NULL,
	expires_at TIMESTAMPTZ NOT NULL
);

-- Sweeping expired challenges is a cheap range scan on this index.
CREATE INDEX auth_challenges_expiry_idx ON auth_challenges (expires_at);

CREATE TABLE daily_results (
	id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id    UUID    NOT NULL REFERENCES users (id) ON DELETE CASCADE,
	date       DATE    NOT NULL,
	difficulty INTEGER NOT NULL CHECK (difficulty BETWEEN 1 AND 5),
	-- Restarts are unlimited after a failure; SOLVED locks the date (spec 8.2).
	attempt_no INTEGER NOT NULL CHECK (attempt_no >= 1),
	outcome    TEXT    NOT NULL CHECK (outcome IN ('SOLVED', 'FAILED')),
	elapsed_ms BIGINT  NOT NULL CHECK (elapsed_ms >= 0),
	mistakes   INTEGER NOT NULL DEFAULT 0 CHECK (mistakes >= 0),
	hints_used INTEGER NOT NULL DEFAULT 0 CHECK (hints_used >= 0),
	-- Whether the solve-order replay check passed.
	verified   BOOLEAN NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	UNIQUE (user_id, date, difficulty, attempt_no)
);

-- Rows are folded into stats and pruned once the day has rolled over; this index drives both.
CREATE INDEX daily_results_date_idx ON daily_results (date);

CREATE TABLE streaks (
	user_id             UUID PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
	-- Named *_streak rather than the spec's bare current/longest: "current" is a SQL keyword and
	-- quoting it at every call site is worse than the two extra words.
	current_streak      INTEGER NOT NULL DEFAULT 0 CHECK (current_streak >= 0),
	longest_streak      INTEGER NOT NULL DEFAULT 0 CHECK (longest_streak >= 0),
	last_completed_date DATE
);

CREATE TABLE stats (
	user_id             UUID    NOT NULL REFERENCES users (id) ON DELETE CASCADE,
	size                INTEGER NOT NULL CHECK (size IN (4, 6, 9, 12, 16)),
	variant             TEXT    NOT NULL CHECK (variant IN ('CLASSIC', 'CHAOS')),
	-- 6 = LISA, which is single-player only but does appear in personal statistics.
	difficulty          INTEGER NOT NULL CHECK (difficulty BETWEEN 1 AND 6),
	games_played        INTEGER NOT NULL DEFAULT 0 CHECK (games_played >= 0),
	solved              INTEGER NOT NULL DEFAULT 0 CHECK (solved >= 0),
	failed              INTEGER NOT NULL DEFAULT 0 CHECK (failed >= 0),
	best_time_ms        BIGINT,
	-- The running total, not the mean: an average cannot be merged incrementally without it.
	-- Average time = total_time_ms / solved.
	total_time_ms       BIGINT  NOT NULL DEFAULT 0 CHECK (total_time_ms >= 0),
	hints_used          INTEGER NOT NULL DEFAULT 0 CHECK (hints_used >= 0),
	PRIMARY KEY (user_id, size, variant, difficulty)
);

CREATE TABLE daily_leaderboard (
	date       DATE    NOT NULL,
	difficulty INTEGER NOT NULL CHECK (difficulty BETWEEN 1 AND 5),
	user_id    UUID    NOT NULL REFERENCES users (id) ON DELETE CASCADE,
	elapsed_ms BIGINT  NOT NULL CHECK (elapsed_ms >= 0),
	attempts   INTEGER NOT NULL DEFAULT 1 CHECK (attempts >= 1),
	-- Recorded but never exposed in the ranking response (spec 8.6).
	hints_used INTEGER NOT NULL DEFAULT 0 CHECK (hints_used >= 0),
	PRIMARY KEY (date, difficulty, user_id)
);

-- Ranking within one tier; pruned at rollover after stats have been updated.
CREATE INDEX daily_leaderboard_rank_idx ON daily_leaderboard (date, difficulty, elapsed_ms);

CREATE TABLE matches (
	id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	mode          TEXT    NOT NULL CHECK (mode IN ('RACE', 'DUEL', 'COOP')),
	state         TEXT    NOT NULL CHECK (state IN ('CREATED', 'WAITING', 'RUNNING', 'ENDED', 'ABANDONED')),
	creator_id    UUID    NOT NULL REFERENCES users (id) ON DELETE CASCADE,
	size          INTEGER NOT NULL CHECK (size IN (4, 6, 9, 12, 16)),
	variant       TEXT    NOT NULL CHECK (variant IN ('CLASSIC', 'CHAOS')),
	-- LISA (6) is rejected for every multiplayer mode (spec 10.1), so the CHECK stops at 5.
	difficulty    INTEGER NOT NULL CHECK (difficulty BETWEEN 1 AND 5),
	-- The PuzzleKey seed; the grid itself is never stored or sent (spec 1).
	seed          BIGINT  NOT NULL,
	lives_enabled BOOLEAN NOT NULL DEFAULT FALSE,
	-- No minimum, no maximum (spec 9a.3). 0 means anyone may join.
	stake         INTEGER NOT NULL DEFAULT 0 CHECK (stake >= 0),
	invite_token  TEXT    NOT NULL,
	winner_id     UUID REFERENCES users (id) ON DELETE SET NULL,
	end_reason    TEXT,
	created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
	started_at    TIMESTAMPTZ,
	ended_at      TIMESTAMPTZ
);

-- Crash recovery on startup scans for matches left RUNNING (spec 9a.3).
CREATE INDEX matches_state_idx ON matches (state);

CREATE TABLE match_participants (
	match_id  UUID        NOT NULL REFERENCES matches (id) ON DELETE CASCADE,
	user_id   UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
	joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	result    TEXT CHECK (result IN ('WON', 'LOST', 'DRAW', 'ABANDONED')),
	PRIMARY KEY (match_id, user_id)
);

CREATE INDEX match_participants_user_idx ON match_participants (user_id);

CREATE TABLE currency_ledger (
	id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id    UUID    NOT NULL REFERENCES users (id) ON DELETE CASCADE,
	delta      INTEGER NOT NULL,
	reason     TEXT    NOT NULL CHECK (reason IN ('EARN_GAME', 'EARN_DAILY', 'STAKE', 'PAYOUT', 'REFUND', 'SYNC_ADJUST')),
	match_id   UUID REFERENCES matches (id) ON DELETE SET NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Balance is derived as SUM(delta) and never stored as a mutable column (spec 5.1).
CREATE INDEX currency_ledger_balance_idx ON currency_ledger (user_id, id);
CREATE INDEX currency_ledger_history_idx ON currency_ledger (user_id, created_at);
