package net.luis.sudoku.repository;

import net.luis.sudoku.db.schema.Schema.PuzzlePoolRow;
import net.luis.sudoku.difficulty.Difficulty;
import net.luis.sudoku.grid.GridSize;
import net.luis.sudoku.grid.Variant;
import net.luis.utils.io.database.Sql;
import net.luis.utils.io.database.exception.SqlException;
import net.luis.utils.io.database.transaction.SqlTransaction;
import org.jspecify.annotations.NonNull;

import java.util.List;

import static net.luis.sudoku.db.schema.Schema.*;

/**
 * Reads and writes {@code puzzle_pool}, the durable half of {@code PuzzleQueue}'s pre-generation pool.
 * <p>
 * <strong>A claim is a hand-off, not a read.</strong> Every row in this table is a puzzle that has not been
 * given to anybody yet, so claiming one has to remove it in the same breath - two instances that both
 * <em>read</em> the oldest row would put two players on the same grid with the same seed, and in a match
 * that is the same board handed out as two independent games. {@link #claim} therefore locks the rows it
 * selects and deletes them before the transaction it runs in commits.
 * <p>
 * <strong>Why {@code FOR UPDATE SKIP LOCKED} and not {@code DELETE ... RETURNING}.</strong> Both are
 * atomic, and the LUtils query builder can express both - {@code SqlDeleteQuery.returning()} exists. The
 * lock form is chosen for what happens under contention rather than for correctness: with a plain
 * {@code DELETE ... WHERE id IN (SELECT ... LIMIT 1)} two instances racing on the same bucket pick the same
 * row, one deletes it and the other comes back empty and generates inline - a miss on a pool that was not
 * actually empty. {@code SKIP LOCKED} makes the second one walk past the locked row to the next available
 * one, so a contended bucket serves both callers from the pool instead of one of them from the CPU. Neither
 * needed a line of hand-written SQL.
 */
public final class PuzzlePoolRepository {
	
	/**
	 * Takes up to {@code limit} pooled puzzles for this bucket, removing them from the pool.
	 * <p>
	 * Rows at any other {@code genVersion} are invisible here rather than merely deprioritised: a puzzle
	 * generated by a different build is not this build's puzzle, and serving one would put a client on a
	 * grid its own shared-core regenerates differently. {@link #deleteOtherGenVersions} clears them out.
	 * <p>
	 * Must run inside a writable transaction that the caller commits promptly. The row locks this takes are
	 * held until it does, and every other instance's claim on the same bucket skips past them meanwhile -
	 * which is harmless for a transaction that ends in milliseconds and a lost pool hit for one that does
	 * not, so nothing slow belongs between this call and the commit.
	 *
	 * @param transaction The caller's transaction
	 * @param size The grid size
	 * @param variant The region layout variant
	 * @param difficulty The target band
	 * @param genVersion The generator version the caller can actually use
	 * @param limit How many to take at most
	 * @return The claimed rows, oldest first, possibly fewer than asked for and possibly none
	 */
	public @NonNull List<PuzzlePoolRow> claim(
		@NonNull SqlTransaction transaction, @NonNull GridSize size, @NonNull Variant variant, @NonNull Difficulty difficulty, int genVersion, int limit
	) throws SqlException {
		if (limit <= 0) {
			return List.of();
		}
		
		List<PuzzlePoolRow> rows = transaction.from(PUZZLE_POOL).select()
			.where(Sql.equalTo(POOL_SIZE, size))
			.where(Sql.equalTo(POOL_VARIANT, variant))
			.where(Sql.equalTo(POOL_DIFFICULTY, difficulty))
			.where(Sql.equalTo(POOL_GEN_VERSION, genVersion))
			.orderBy(POOL_ID.ascending())
			.limit(limit)
			.forUpdate()
			.skipLocked()
			.fetch();
		if (rows.isEmpty()) {
			return List.of();
		}
		
		// By id rather than by the bucket again: the SELECT already decided which rows these are, and
		// re-stating the predicate would delete rows this claim never locked.
		Long[] claimed = rows.stream().map(PuzzlePoolRow::id).toArray(Long[]::new);
		transaction.from(PUZZLE_POOL).delete().where(Sql.in(POOL_ID, claimed)).execute();
		return rows;
	}
	
	/**
	 * Adds freshly generated puzzles to the pool.
	 * <p>
	 * The rows carry an {@code id} that is never rendered - the column is declared {@code autoIncrement()} -
	 * so whatever the caller put there is ignored, exactly as for {@code currency_ledger}.
	 *
	 * @param transaction The caller's transaction
	 * @param rows The rows to append
	 */
	public void store(@NonNull SqlTransaction transaction, @NonNull List<PuzzlePoolRow> rows) throws SqlException {
		for (PuzzlePoolRow row : rows) {
			transaction.from(PUZZLE_POOL).insert(row).execute();
		}
	}
	
	/**
	 * @return how many usable puzzles this bucket holds, which is what decides how many more to generate
	 */
	public int count(@NonNull SqlTransaction transaction, @NonNull GridSize size, @NonNull Variant variant, @NonNull Difficulty difficulty, int genVersion) throws SqlException {
		return (int) transaction.from(PUZZLE_POOL).select()
			.where(Sql.equalTo(POOL_SIZE, size))
			.where(Sql.equalTo(POOL_VARIANT, variant))
			.where(Sql.equalTo(POOL_DIFFICULTY, difficulty))
			.where(Sql.equalTo(POOL_GEN_VERSION, genVersion))
			.count();
	}
	
	/**
	 * Deletes every pooled puzzle that some other generator version produced.
	 * <p>
	 * Deleted rather than left for {@link #claim} to filter out: they can never become servable again -
	 * {@code genVersion} only ever moves forward - so keeping them would be keeping rows that are already
	 * known to be dead, in a table whose whole size budget is "a few dozen per bucket in use".
	 *
	 * @return how many rows were removed, which is worth logging because it means a generator change shipped
	 */
	public int deleteOtherGenVersions(@NonNull SqlTransaction transaction, int genVersion) throws SqlException {
		return transaction.from(PUZZLE_POOL).delete().where(Sql.equalTo(POOL_GEN_VERSION, genVersion).not()).execute();
	}
}
